# Use the official MySQL Docker image as the base image
FROM mysql:latest

# Set environment variables for MySQL configuration
ENV MYSQL_DATABASE=accwe-hospital
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root
ENV MYSQL_ROOT_PASSWORD=root

# Expose the default MySQL port
EXPOSE 3306

# Set the default command to run when the container starts
CMD ["mysqld"]